name: Build and Deploy Task App

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - 'package.json'
      - 'vite.config.ts'
      - 'tsconfig.json'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Verify build output
        run: |
          if [ ! -d "dist" ]; then
            echo "❌ Error: Build output directory 'dist' not found!"
            exit 1
          fi

          if [ ! -f "dist/index.js" ]; then
            echo "❌ Error: dist/index.js was not created"
            exit 1
          fi

          if [ ! -s "dist/index.js" ]; then
            echo "❌ Error: dist/index.js is empty"
            exit 1
          fi

          if [ ! -f "dist/style.css" ]; then
            echo "❌ Error: dist/style.css was not created"
            exit 1
          fi

          if [ ! -s "dist/style.css" ]; then
            echo "❌ Error: dist/style.css is empty"
            exit 1
          fi

          echo "✅ Build output found:"
          ls -la dist
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-dist
          path: dist/
          retention-days: 30
      
      - name: Trigger parent site deployment
        env:
          HADOKU_SITE_TOKEN: ${{ secrets.HADOKU_SITE_TOKEN }}
        run: |
          echo "Triggering hadoku_site deployment..."
          if [ -z "$HADOKU_SITE_TOKEN" ]; then
            echo "❌ Error: HADOKU_SITE_TOKEN secret is not available."
            exit 1
          fi

          payload=$(cat <<EOF
            {
              "event_type": "task_updated",
              "client_payload": {
                "run_id": "${{ github.run_id }}",
                "sha": "${{ github.sha }}",
                "ref": "${{ github.ref }}"
              }
            }
          EOF
          )

          response_file=$(mktemp)
          trap 'rm -f "$response_file"' EXIT

          status_code=$(curl -sS \
            -o "$response_file" \
            -w "%{http_code}" \
            -X POST "https://api.github.com/repos/WolffM/hadoku_site/dispatches" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $HADOKU_SITE_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$payload")

          if [ "$status_code" != "204" ]; then
            echo "❌ Failed to trigger hadoku_site deployment (HTTP $status_code)"
            cat "$response_file"
            rm -f "$response_file"
            exit 1
          fi

          echo "✅ Triggered hadoku_site deployment with run_id: ${{ github.run_id }}"
          rm -f "$response_file"
