name: Build and Publish UI

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/ui/**'
      - 'packages/shared/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build shared package
        run: pnpm --filter @watchparty/shared build
      
      - name: Build UI
        run: pnpm --filter watchparty-ui build
      
      - name: Commit dist files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add apps/ui/dist/
          git diff --staged --quiet || git commit -m "chore: build watchparty UI [skip ci]"
          git push
      
      - name: Purge jsDelivr cache
        run: |
          curl -f "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/apps/ui/dist/index.js" || echo "Cache purge failed but continuing"
      
      - name: Trigger hadoku_site deployment
        if: success()
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.HADOKU_SITE_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/WolffM/hadoku_site/dispatches \
            -d '{"event_type":"watchparty_updated","client_payload":{"commit":"${{ github.sha }}"}}'
